### ISSUE TITLE
dub master cannot be built by older compilers

### ISSUE THREAD

**Issue by ibuclaw** [dlang/dub#2391]
The stable branch can be built by compilers based on 2.076.x (i.e: gdc-11).  But master fails to build with anything younger than 2.099.x.

dmd 2.098:
```
source/dub/dub.d(746): Error: expression expected, not `throw`
source/dub/dub.d(746): Error: found `new` when expecting `)` following template argument list
source/dub/dub.d(746): Error: semicolon expected following auto declaration, not `Exception`
source/dub/dub.d(747): Error: expression expected, not `)`
```

**Comment by Geod24** [comment]
I don't think we should support v2.076, but we should support the last 10 versions. That looks like a rather simple fix.

**Comment by Geod24** [comment]
It's not a simple fix. Since we are using `std.sumtype`, which is in Phobos only since v2.097.0, it creates a lot of issues.
Using `dyaml.stdsumtype` leads to other problems.

**Comment by maxhaton** [comment]
Hack it with `-mv`?

**Comment by Geod24** [comment]
> Using `dyaml.stdsumtype` leads to other problems.

`-mv` is never the answer. And as I mentioned:

> Using `dyaml.stdsumtype` leads to other problems.

**Comment by SingingBush** [comment]
2.097 and above is still better than 2.099 and above. Probably worth just going with that and putting

```
frontend=">=2.097"
```

In the dub.sdl

**Comment by ibuclaw** [comment]
DMD nightly builds are the latest victim of this issue.

https://github.com/dlang/dmd/actions/workflows/nightlies.yml
