### ISSUE TITLE
dub run --build=ddox not working

### ISSUE THREAD

**Issue by grogancolin** [dlang/dub#1150]
I can't seem to build a ddox build of my project.

`dub run --build=ddox` errors out with the following:
```
Performing "debug" build using dmd for x86_64.
hyphenate 1.1.1: target for configuration "library" is up to date.
libdparse 0.7.0-beta.2: target for configuration "library" is up to date.
vibe-d:utils 0.7.30: target for configuration "library" is up to date.
vibe-d:data 0.7.30: target for configuration "library" is up to date.
vibe-d:core 0.7.30: building configuration "libevent"...
../../.dub/packages/vibe-d-0.7.30/vibe-d/source/vibe/core/core.d(1183,18): Error: function vibe.core.core.CoreTask.state cannot override final function core.thread.Fiber.state
dmd failed with exit code 1.
```

```
$ dmd --version
DMD64 D Compiler v2.074.1
Copyright (c) 1999-2017 by Digital Mars written by Walter Bright

$ dub --version
DUB version 1.3.0, built on May 31 2017
```

Maybe ddox needs to use a newer version of vibe-d ?

**Comment by wilzbach** [comment]
It already has: https://github.com/rejectedsoftware/ddox/blob/master/dub.selections.json

You seem to have 0.7.30 installed locally and for some reason this is preferred, even though the `dub.sdl` of Ddox requires a higher version:

https://github.com/rejectedsoftware/ddox/blob/master/dub.sdl

To resolve your problem I recommend nuking `~/.dub`, but there seems to be a general problem with matching required dependencies ...

**Comment by MartinNowak** [comment]
Ddox is built separately and doesn't pick up dub.selections.json from your package.
What it does though is building whatever ddox version is already fetched https://github.com/dlang/dub/blob/68d4f51e7b903e547621b5e53a40434fe7874d8a/source/dub/dub.d#L1066.
Running `dub fetch ddox` will update the max available version.
Since the ddoxTool is selectable (see https://github.com/MartinNowak/scod) we can't hardcode the tool version in dub (and wouldn't want to anyhow).

Any good idea how to integrate ddoxTool upgrades into the workflow?

**Comment by makechip** [comment]
Tried the above fixes, and now I get this error:
../../.dub/packages/vibe-d-0.7.31/vibe-d/source/vibe/http/server.d(1715,32): Error: variable vibe.http.server.handleHTTPConnection.tls_stream variables cannot be of type void

**Comment by tetianakh** [comment]
Hi, I've got the same error in my project when running `dub build`. Executing `find -name dub.selections.json | xargs rm` solved the problem for me.

**Comment by ohdatboi** [comment]
Closed due to inactivity. If somebody experiences similar problems, open a new issue.
