### ISSUE TITLE
SDLang not compilable with 2.072.1-b1

### ISSUE THREAD

**Issue by MartinNowak** [dlang/dub#960]
Don't yet understand why I get this error only locally but not on Travis-CI.
https://travis-ci.org/dlang/dub/jobs/164950627

The std.stream module was removed, but SDL still depends on it to strip BOM.
`source/dub/internal/sdlang/lexer.d(16,8): Error: module stream is in file 'std/stream.d' which cannot be read`

Wasn't there a dub package for SDL by now?

**Comment by s-ludwig** [comment]
I committed a fix to master and will push to stable, too: 1c0888c31834f91598c0ec68ebec0ee7308281e1
The current version of the DUB package only compiles on 2.070.x and above (AFAIR) and is difficult to get to work on <2.068.x. See #949. But the main reason why a local copy is used is to make bootstrapping more robust and simple. However, once the sdlang-d dependency is present, it will automatically be used (there are `version (Have_sdlang_d)` statements in each duplicated module.

**Comment by s-ludwig** [comment]
Compiles now. However, one test fails at runtime, maybe a Phobos or DMD regression.
