### PR TITLE
Maven repository package supplier added

### PR DESCRIPTION
**Pull request by andre2007**
The purpose of this pull request is to be a door opener for dub in commercial sector. In build infrastructure it is in many cases not allowed to connect to the public internet (code.dlang.org) for security reasons. Instead the companies runs their own repositories using software like Nexus or Artifactory.
It is quite hard to convince system administrators to also run additional software like dub registry.

To solve this problem, this pull request enables dub to connect to maven repositories to retrieve dub packages. Environment variable ```DUB_REGISTRY``` and console argument ```--registry``` now accepts additional protocols (dub/mvn). Example:

--registry dub+https://code.dlang.org
--registry mvn+http://localhost:8040/artifactory/libs-release/dubpackages

These Maven urls consists of the path to a maven repository + a group id. 
(libs-release is the maven repository, dubpackages is the group id)

In the maven repository you deploy your dub package with group id "dubpackages" and
as artifactId you use dub package name and as version you use dub package version.

Maven creates a metadata xml file which get quite handy for retrieving metadata needed for dub
```
<?xml version="1.0" encoding="UTF-8"?>
<metadata modelVersion="1.1.0">
  <groupId>dubpackages</groupId>
  <artifactId>d-unit</artifactId>
  <version>0.8.2</version>
  <versioning>
    <latest>0.8.2</latest>
    <release>0.8.2</release>
    <versions>
      <version>0.8.2</version>
    </versions>
    <lastUpdated>20180317184845</lastUpdated>
  </versioning>
</metadata>
```
This metadata and the archives (zip)files are stored using canonical paths.
http://localhost:8040/artifactory/libs-release/dubpackages/d-unit/maven-metadata.xml
http://localhost:8040/artifactory/libs-release/dubpackages/d-unit/0.8.2/d-unit-0.8.2.zip

As far as I know Maven does not provide a nice generic way to implement the searchPackages method.
Therefore I left this method empty.

Can you have a look at this pr?

### CODE REVIEW

**Comment by andre2007** [comment]
Test added

**Comment by s-ludwig** [comment]
Didn't review the code in detail, yet, but from the outside everything looks good. Considering that there have been additional proposals for extended repository support, maybe we should start thinking about how to generalize the registry protocol specification, could for example be a prefix (`maven,https://...`) or part of the schema (`maven+https://...` or `dub+https://...`).

**Comment by andre2007** [comment]
I really like the "maven+https://" proposal. This makes the additional console argument and env variable superfluous. I will adapt the coding.

**Comment by andre2007** [comment]
The new logic does not work due to bug #1418

File: source/dub/dub.d [hunk 1]
```diff
@@ -87,6 +87,37 @@ PackageSupplier[] defaultPackageSuppliers()
 	];
 }
 
+/** Returns a registry package supplier according to protocol.
+
+	Allowed protocols are dub+http(s):// and maven+http(s)://.
+*/
+PackageSupplier getRegistryPackageSupplier(string url)
```
Comment (andre2007) [inline source/dub/dub.d]: I worked around bug #1418 by adapting the string before creating URL.
If this is OK I would leave the method as it is and solve the bug in URL in an independent pr.

**Comment by andre2007** [comment]
What is your preference?
- mvn+https://
- maven+https://
- m2+https://

**Comment by wilzbach** [comment]
> What is your preference?

mvn+https://

**Comment by andre2007** [comment]
I changed to protocol mvn+https.
Ready for review:)

File: source/dub/dub.d [hunk 2]
```diff
@@ -87,6 +87,37 @@ PackageSupplier[] defaultPackageSuppliers()
...
+{
+	if (url.toLower.startsWith("dub+"))
```
Comment (wilzbach) [inline source/dub/dub.d]: 1) avoid the allocation -> `asLowerCase`
2) Do we even need lowering? 
3) You could make this generic and faster (`startsWith` supports a variadic overload for better performance as the string checking is only done once)

```d
import std.algorithm : map;
import std.meta : aliasSeqOf;
enum needles = [
	["dub+", "RegistryPackageSupplier"],
	["maven+", "M2RegistryPackageSupplier"],
];
switch(url.startsWith(aliasSeqOf!(map!(a => a[0])(needles))))
{
	static foreach (uint i, el; needles)
		case i + 1:
			mixin("return new "~ el[1] ~"(URL(url["~el.length.to!string~"0 .. $]));");
	default:
		return new RegistryPackageSupplier(URL(url));
} 
```

edit: you probably can't use `static foreach` yet as GDC doesn't support this yet, but the "normal" CTFE foreach works as well.

File: test/test_maven_registry.d [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+	immutable port = readRequiredOption!uint("port", "Port to use");
+	auto router = new URLRouter;
+	router.get("stop", (HTTPServerRequest req, HTTPServerResponse res){
+		res.writeVoidBody;
+		exitEventLoop();
+	});
+	router.get("*", folder.serveStaticFiles);
+	listenHTTP(text(":", port), router);
+	runApplication();
+}
```
Comment (wilzbach) [inline test/test_maven_registry.d]: Might be worthwhile to look into whether the duplication from `test_registry.d` can be avoided.
Maybe a switch to make fallbacks optional?
Though OTOH it might be a good idea to check whether the retry logic actually works.

File: test/test_maven_registry.d [hunk 4]
```diff
@@ -0,0 +1,19 @@
+/+dub.sdl:
+dependency "vibe-d" version="~>0.8.3-alpha.1"
```
Comment (wilzbach) [inline test/test_maven_registry.d]: 0.8.3 has been released for a while now.

File: test/issue1416-maven-repo-pkg-supplier.sh [hunk 5]
```diff
@@ -0,0 +1,21 @@
...
+"$DIR"/test_maven_registry --folder="$DIR/issue1416-maven-repo-pkg-supplier" --port=$PORT &
+PID=$!
+sleep 1
+trap 'kill $PID 2>/dev/null || true' exit
+
+echo "Trying to download maven-dubpackage (1.0.5)"
+"$DUB" fetch maven-dubpackage --version=1.0.5 --skip-registry=all --registry=mvn+http://localhost:$PORT/maven/release/dubpackages
+
+if ! dub remove maven-dubpackage --non-interactive --version=1.0.5 2>/dev/null; then
+    die 'DUB not have installed package from maven registry.'
```
Comment (wilzbach) [inline test/issue1416-maven-repo-pkg-supplier.sh]: Spelling:

- DUB did not install
- DUB doesn't have the installed

File: source/dub/packagesupplier.d [hunk 6]
```diff
@@ -290,6 +290,150 @@ class RegistryPackageSupplier : PackageSupplier {
...
+	Maven repository based package supplier.
+
+	This package supplier connects to a maven repository
+	to search for available packages.
+*/
+class MavenRegistryPackageSupplier : PackageSupplier {
+	private {
+		URL m_mavenUrl;
+		struct CacheEntry { Json data; SysTime cacheTime; }
+		CacheEntry[string] m_metadataCache;
```
Comment (wilzbach) [inline source/dub/packagesupplier.d]: When only new packages are added this cache is never cleared. It doubt it matters because usage is through one-time CLI mostly + there are less than a million MVN packages.

File: source/dub/packagesupplier.d [hunk 7]
```diff
@@ -290,6 +290,150 @@ class RegistryPackageSupplier : PackageSupplier {
...
+	override @property string description() { return "maven repository at "~m_mavenUrl.toString(); }
+
+	Version[] getVersions(string package_id)
+	{
+		auto md = getMetadata(package_id);
+		if (md.type == Json.Type.null_)
+			return null;
+		Version[] ret;
+		foreach (json; md["versions"]) {
+			auto cur = Version(cast(string)json["version"]);
```
[the remark this answers is not in the document]
Comment (andre2007) [reply source/dub/packagesupplier.d]: done

File: source/dub/packagesupplier.d [hunk 8]
```diff
@@ -290,6 +290,150 @@ class RegistryPackageSupplier : PackageSupplier {
...
+		import std.xml;
+
+		auto now = Clock.currTime(UTC());
+		if (auto pentry = packageId in m_metadataCache) {
+			if (pentry.cacheTime + m_maxCacheTime > now)
+				return pentry.data;
+			m_metadataCache.remove(packageId);
+		}
+
+		auto url = m_mavenUrl~ NativePath(packageId ~ "/maven-metadata.xml");
```
[the remark this answers is not in the document]
Comment (andre2007) [reply source/dub/packagesupplier.d]: done

File: source/dub/packagesupplier.d [hunk 9]
```diff
@@ -290,6 +290,150 @@ class RegistryPackageSupplier : PackageSupplier {
...
+
+	private Json getBestPackage(string packageId, Dependency dep, bool pre_release)
+	{
+		Json md = getMetadata(packageId);
+		if (md.type == Json.Type.null_)
+			return md;
+		Json best = null;
+		Version bestver;
+		foreach (json; md["versions"]) {
+			auto cur = Version(cast(string)json["version"]);
```
[the remark this answers is not in the document]
Comment (andre2007) [reply source/dub/packagesupplier.d]: done

File: source/dub/packagesupplier.d [hunk 10]
```diff
@@ -290,6 +290,150 @@ class RegistryPackageSupplier : PackageSupplier {
...
+			if (!dep.matches(cur)) continue;
+			if (best == null) best = json;
+			else if (pre_release) {
+				if (cur > bestver) best = json;
+			} else if (bestver.isPreRelease) {
+				if (!cur.isPreRelease || cur > bestver) best = json;
+			} else if (!cur.isPreRelease && cur > bestver) best = json;
+			bestver = Version(cast(string)best["version"]);
```
[the remark this answers is not in the document]
Comment (andre2007) [reply source/dub/packagesupplier.d]: done

File: test/issue1416-maven-repo-pkg-supplier.sh (hunk 5 above)
Comment (andre2007) [reply test/issue1416-maven-repo-pkg-supplier.sh]: done

**Comment by andre2007** [comment]
Thanks for your comments, the easy ones I already solved, the others will take some time.

- The MavenRegistry cache logic is copy paste from RegistryPackageSupplier, the out of memory issue might occurs here too.

- I will check whether I can enhance the download method as proposed by you

- This will not compile with error: variable i & el not available at compile time. I will have a deeper look

```
import std.algorithm : map;
import std.meta : aliasSeqOf;
enum needles = [
	["dub+", "RegistryPackageSupplier"],
	["maven+", "M2RegistryPackageSupplier"],
];
switch(url.startsWith(aliasSeqOf!(map!(a => a[0])(needles))))
{
	foreach (uint i, el; needles)
		case i + 1:
			mixin("return new "~ el[1] ~"(URL(url["~el.length.to!string~"0 .. $]));");
	default:
		return new RegistryPackageSupplier(URL(url));
} 
```

**Comment by wilzbach** [comment]
> This will not compile with error: variable i & el not available at compile time. I will have a deeper look

Oh I just used `static foreach`, because I more used to it: https://run.dlang.io/is/c3Axuv
For legacy support with CTFE foreach you need to use an AliasSeq in the foreach, e.g. by `aliasSeqOf`: https://run.dlang.io/is/zg9ca2

File: test/test_maven_registry.d (hunk 4 above)
Comment (andre2007) [reply test/test_maven_registry.d]: By changing to 0.8.3 there are some failing tests:
Root package test_maven_registry reference vibe-d ~>0.8.3 cannot be satisfied.
https://travis-ci.org/dlang/dub/jobs/357730493

File: source/dub/packagesupplier.d [hunk 11]
```diff
@@ -290,6 +290,150 @@ class RegistryPackageSupplier : PackageSupplier {
...
+		auto md = getMetadata(package_id);
+		if (md.type == Json.Type.null_)
+			return null;
+		Version[] ret;
+		foreach (json; md["versions"]) {
+			auto cur = Version(cast(string)json["version"]);
+			ret ~= cur;
+		}
+		ret.sort();
+		return ret;
```
[the remark this answers is not in the document]
Comment (andre2007) [reply source/dub/packagesupplier.d]: Should be covered now. An additional test was added to issue1416-maven-repo-pkg-supplier.sh which should retrieve the latest version.

File: test/test_maven_registry.d (hunk 3 above)
Comment (andre2007) [reply test/test_maven_registry.d]: You are right, I removed this file and use test_registry.d instead

**Comment by andre2007** [comment]
I tried to generalize the download retry but I didn't found a nice way. By generalizing you loose the dedicated error/log statements:
Error getting metadata for package...
Package %s not found at...
Maven metadata %s not found...

There is one failing test, s.th. about ddoc, I am not really sure what is the cause:
```
etching libdparse 0.7.1 (getting selected version)...
Failed to extract zip archive for libdparse 0.7.1...
Failed to extract zip archive for libdparse 0.7.1...
Failed to extract zip archive for libdparse 0.7.1...
ZipException: no end record
[ERROR] /home/travis/build/dlang/dub/test/ddox.sh:11 command failed
[ERROR] /home/travis/build/dlang/dub/test/ddox.sh:11 command failed
[ERROR] Script failure.
```

https://travis-ci.org/dlang/dub/jobs/357735491

**Comment by andre2007** [comment]
Failing test cause by:
```
[INFO] Running /home/travis/build/dlang/dub/test/issue1416-maven-repo-pkg-supplier.sh...
Fetching libevent 2.0.2+2.0.16 (getting selected version)...
Fetching diet-ng 1.4.5 (getting selected version)...
Fetching taggedalgebraic 0.10.11 (getting selected version)...
Fetching openssl 1.1.6+1.0.1g (getting selected version)...
Fetching botan 1.12.9 (getting selected version)...
Fetching stdx-allocator 2.77.0 (getting selected version)...
Fetching vibe-d 0.8.3 (getting selected version)...
Fetching memutils 0.4.10 (getting selected version)...
Fetching vibe-core 1.4.0 (getting selected version)...
Fetching libasync 0.8.3 (getting selected version)...
Fetching botan-math 1.0.3 (getting selected version)...
Fetching eventcore 0.8.34 (getting selected version)...
Performing "debug" build using dmd for x86_64.
taggedalgebraic 0.10.11: building configuration "library"...
eventcore 0.8.34: building configuration "epoll"...
../../../.dub/packages/eventcore-0.8.34/eventcore/source/eventcore/drivers/posix/driver.d(145,14): Error: safe function 'eventcore.drivers.posix.driver.PosixEventDriverCore!(SelectEventLoop, LoopTimeoutTimerDriver, PosixEventDriverEvents!(SelectEventLoop, PosixEventDriverSockets!(SelectEventLoop))).PosixEventDriverCore.dispose' cannot call system function 'core.atomic.atomicStore!(cast(MemoryOrder)3, Mutex, typeof(null)).atomicStore'
```

File: source/dub/dub.d (hunk 2 above)
Comment (andre2007) [reply source/dub/dub.d]: done

**Comment by andre2007** [comment]
@wilzbach 
unfortunately the solution with aliasSeqOf does not work on dmd 2.069.2 and 2.068.2:
```
 Error: module std.meta import 'aliasSeqOf' not found
```
My proposal is to have a straight forward solution. I will update the pr

**Comment by andre2007** [comment]
Any chance to get this pr tagged for 1.9.0?

**Comment by wilzbach** [comment]
> Any chance to get this pr tagged for 1.9.0?

Done. I don't see any bigger issues, so this should hopefully work out :)

File: source/dub/packagesupplier.d [hunk 12]
```diff
@@ -290,6 +290,150 @@ class RegistryPackageSupplier : PackageSupplier {
...
+				return;
+			}
+			catch(HTTPStatusException e) {
+				if (e.status == 404) throw e;
+				else {
+					logDebug("Failed to download package %s from %s (Attempt %s of 3)", packageId, url, i + 1);
+					continue;
+				}
+			}
+		}
```
[the remark this answers is not in the document]
Comment (WebFreak001) [reply source/dub/packagesupplier.d]: or a retrying download function

File: source/dub/packagesupplier.d [hunk 13]
```diff
@@ -266,27 +268,129 @@ class RegistryPackageSupplier : PackageSupplier {
...
+
+	Json fetchPackageRecipe(string packageId, Dependency dep, bool pre_release)
+	{
+		auto md = getMetadata(packageId);
+		return getBestPackage(md, packageId, dep, pre_release);
+	}
+
+	private Json getMetadata(string packageId)
+	{
+		import std.xml;
```
Comment (WebFreak001) [inline source/dub/packagesupplier.d]: not sure if it's a good idea to import this, vibe should really contain something for xml or at least html parsing

File: test/issue1416-maven-repo-pkg-supplier/maven/release/dubpackages/maven-dubpackage/maven-metadata.xml [hunk 14]
```diff
@@ -0,0 +1,14 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<metadata modelVersion="1.1.0">
+  <groupId>dubpackages</groupId>
+  <artifactId>maven-dubpackage</artifactId>
+  <versioning>
+    <latest>1.0.6</latest>
+    <release>1.0.6</release>
+    <versions>
+      <version>1.0.5</version>
+	  <version>1.0.6</version>
```
Comment (WebFreak001) [inline test/issue1416-maven-repo-pkg-supplier/maven/release/dubpackages/maven-dubpackage/maven-metadata.xml]: mixed tab and space here

Comment (andre2007) [reply test/issue1416-maven-repo-pkg-supplier/maven/release/dubpackages/maven-dubpackage/maven-metadata.xml]: done

File: source/dub/packagesupplier.d (hunk 13 above)
Comment (andre2007) [reply source/dub/packagesupplier.d]: I checked, unfortunately vibed doesn't contain anything regarding xml. It would maybe possible to parse the text via regex (Find all child "version" tags within parent tag "versions") or plain string functions. But as phobos contains a xml parsers which works quite well for this scenario, I am not 100% sure.

**Comment by andre2007** [comment]
Do you have a time schedule when this pull request can be merged?
