### ISSUE TITLE
Linker errors when switching from dmd 2.84.* to 2.85.0

### ISSUE THREAD

**Issue by aliak00** [dlang/dub#1665]
### System information

- **dub version**: 1.14
- **OS Platform and distribution**: osx
- **compiler version** 2.085.0

### Bug Description

Linker errors with a specific dub setup. It works when the compiler version is 2.084.* but not when it's 2.085.0. Furthermore, it also works when importing in a different way, but not with the other

### How to reproduce?

Create a new dub project, add `ddash` as a dependency and then:

```
import std.stdio;

void main() {
	import ddash: stringifySeperatedBy;
	writeln([1, 2, 3].stringifySeperatedBy("."));
}
```

If you change the import to:
```
import ddash.algorithm: stringifySeperatedBy;
```

Then it works as expected with dmd 2.085.0

### Expected Behavior

When `dub run` the output should be:
```
Linking...
To force a rebuild of up-to-date targets, run again with --force.
Running ./blah
1.2.3
```

### Logs

```
Using dub registry url 'https://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /Users/aliak/.dub/packages/local-packages.json
Note: Failed to determine version of package blah at .. Assuming ~master.
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /Users/aliak/.dub/packages/local-packages.json
  Found dependency ddash 0.11.1
    Found dependency ddash:range 0.11.1
      Found dependency ddash:common 0.11.1
        Found dependency optional 0.11.1
          Found dependency bolts 0.11.1
          Found dependency silly 0.8.0
        Found dependency sumtype 0.8.3
    Found dependency ddash:utils 0.11.1
      Found dependency ddash:functional 0.11.1
        Found dependency ddash:lang 0.11.1
    Found dependency ddash:algorithm 0.11.1
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /Users/aliak/.dub/packages/local-packages.json
  Found dependency ddash 0.11.1
    Found dependency ddash:range 0.11.1
      Found dependency ddash:common 0.11.1
        Found dependency optional 0.11.1
          Found dependency bolts 0.11.1
          Found dependency silly 0.8.0
        Found dependency sumtype 0.8.3
    Found dependency ddash:utils 0.11.1
      Found dependency ddash:functional 0.11.1
        Found dependency ddash:lang 0.11.1
    Found dependency ddash:algorithm 0.11.1
Generating using build
Configuring dependent blah, deps:"ddash"
  Configuring dependent ddash, deps:"ddash:algorithm", "ddash:functional", "ddash:lang", "ddash:range", "ddash:utils"
    Configuring dependent ddash:algorithm, deps:"ddash:common", "ddash:functional", "ddash:range", "ddash:utils"
      Configuring dependent ddash:common, deps:"optional", "sumtype"
        Configuring dependent optional, deps:"bolts"
          Configuring dependent bolts, deps:
        Configuring dependent sumtype, deps:
      Configuring dependent ddash:functional, deps:"ddash:common", "ddash:lang"
        Configuring dependent ddash:lang, deps:"ddash:common"
      Configuring dependent ddash:range, deps:"ddash:common"
      Configuring dependent ddash:utils, deps:"ddash:common", "ddash:functional", "ddash:lang"
Performing "debug" build using /Library/D/dmd/bin/dmd for x86_64.
bolts 0.11.1: target for configuration "library" is up to date.
Using existing build in /Users/aliak/.dub/packages/bolts-0.11.1/bolts/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-C1A02255D87BA8E244266BB680A12BEE/.
Copying target from /Users/aliak/.dub/packages/bolts-0.11.1/bolts/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-C1A02255D87BA8E244266BB680A12BEE/libbolts.a to /Users/aliak/.dub/packages/bolts-0.11.1/bolts/bin
optional 0.11.1: target for configuration "unittest" is up to date.
Using existing build in /Users/aliak/.dub/packages/optional-0.11.1/optional/.dub/build/unittest-debug-posix.osx-x86_64-dmd_2085-37E1E0E388ECBD0246AD2EFF461E5759/.
Copying target from /Users/aliak/.dub/packages/optional-0.11.1/optional/.dub/build/unittest-debug-posix.osx-x86_64-dmd_2085-37E1E0E388ECBD0246AD2EFF461E5759/liboptional.a to /Users/aliak/.dub/packages/optional-0.11.1/optional/bin
sumtype 0.8.3: target for configuration "library" is up to date.
Using existing build in /Users/aliak/.dub/packages/sumtype-0.8.3/sumtype/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-DCC08B4F3C573EF2293885A580982517/.
Copying target from /Users/aliak/.dub/packages/sumtype-0.8.3/sumtype/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-DCC08B4F3C573EF2293885A580982517/libsumtype.a to /Users/aliak/.dub/packages/sumtype-0.8.3/sumtype
ddash:common 0.11.1: target for configuration "library" is up to date.
Using existing build in /Users/aliak/.dub/packages/ddash-0.11.1/ddash/common/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-DD0F58D7EF71196DD2A1B5B4A5493A33/.
Copying target from /Users/aliak/.dub/packages/ddash-0.11.1/ddash/common/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-DD0F58D7EF71196DD2A1B5B4A5493A33/libddash_common.a to /Users/aliak/.dub/packages/ddash-0.11.1/ddash/bin
ddash:lang 0.11.1: target for configuration "library" is up to date.
Using existing build in /Users/aliak/.dub/packages/ddash-0.11.1/ddash/lang/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-D5C081D96DABDC69079203481376487A/.
Copying target from /Users/aliak/.dub/packages/ddash-0.11.1/ddash/lang/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-D5C081D96DABDC69079203481376487A/libddash_lang.a to /Users/aliak/.dub/packages/ddash-0.11.1/ddash/bin
ddash:functional 0.11.1: target for configuration "library" is up to date.
Using existing build in /Users/aliak/.dub/packages/ddash-0.11.1/ddash/functional/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-045415D91A06B9EA97EF466F23EE2558/.
Copying target from /Users/aliak/.dub/packages/ddash-0.11.1/ddash/functional/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-045415D91A06B9EA97EF466F23EE2558/libddash_functional.a to /Users/aliak/.dub/packages/ddash-0.11.1/ddash/bin
ddash:range 0.11.1: target for configuration "library" is up to date.
Using existing build in /Users/aliak/.dub/packages/ddash-0.11.1/ddash/range/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-4ACB945551464FF2F41E70830C443DEA/.
Copying target from /Users/aliak/.dub/packages/ddash-0.11.1/ddash/range/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-4ACB945551464FF2F41E70830C443DEA/libddash_range.a to /Users/aliak/.dub/packages/ddash-0.11.1/ddash/bin
ddash:utils 0.11.1: target for configuration "library" is up to date.
Using existing build in /Users/aliak/.dub/packages/ddash-0.11.1/ddash/utils/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-37378B094A0203E17D0CC4394DEDEF69/.
Copying target from /Users/aliak/.dub/packages/ddash-0.11.1/ddash/utils/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-37378B094A0203E17D0CC4394DEDEF69/libddash_utils.a to /Users/aliak/.dub/packages/ddash-0.11.1/ddash/bin
ddash:algorithm 0.11.1: target for configuration "library" is up to date.
Using existing build in /Users/aliak/.dub/packages/ddash-0.11.1/ddash/algorithm/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-347F3AC60651BAB598ACCABDD1B134FC/.
Copying target from /Users/aliak/.dub/packages/ddash-0.11.1/ddash/algorithm/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-347F3AC60651BAB598ACCABDD1B134FC/libddash_algorithm.a to /Users/aliak/.dub/packages/ddash-0.11.1/ddash/bin
ddash 0.11.1: target for configuration "unittest" is up to date.
Using existing build in /Users/aliak/.dub/packages/ddash-0.11.1/ddash/.dub/build/unittest-debug-posix.osx-x86_64-dmd_2085-17A0CE6738F65D5CF5A39B0793591577/.
Copying target from /Users/aliak/.dub/packages/ddash-0.11.1/ddash/.dub/build/unittest-debug-posix.osx-x86_64-dmd_2085-17A0CE6738F65D5CF5A39B0793591577/libddash.a to /Users/aliak/.dub/packages/ddash-0.11.1/ddash/bin
File 'source/app.d' modified, need rebuild.
blah ~master: building configuration "application"...
/Library/D/dmd/bin/dmd -c -of.dub/build/application-debug-posix.osx-x86_64-dmd_2085-66874AF3FB189D7222280D5A9FD00EE1/blah.o -debug -g -w -version=Have_blah -version=Have_ddash -version=Have_silly -version=Have_ddash_algorithm -version=Have_ddash_functional -version=Have_ddash_lang -version=Have_ddash_range -version=Have_ddash_utils -version=Have_ddash_common -version=Have_optional -version=Have_sumtype -version=Have_bolts -Isource/ -I../../../.dub/packages/ddash-0.11.1/ddash -I../../../.dub/packages/silly-0.8.0/silly -I../../../.dub/packages/ddash-0.11.1/ddash/algorithm/source/ -I../../../.dub/packages/ddash-0.11.1/ddash/common/source/ -I../../../.dub/packages/optional-0.11.1/optional/source/ -I../../../.dub/packages/optional-0.11.1/optional/tests -I../../../.dub/packages/bolts-0.11.1/bolts/source/ -I../../../.dub/packages/sumtype-0.8.3/sumtype/src/ -I../../../.dub/packages/ddash-0.11.1/ddash/functional/source/ -I../../../.dub/packages/ddash-0.11.1/ddash/lang/source/ -I../../../.dub/packages/ddash-0.11.1/ddash/range/source/ -I../../../.dub/packages/ddash-0.11.1/ddash/utils/source/ source/app.d -vcolumns
Linking...
/Library/D/dmd/bin/dmd -of.dub/build/application-debug-posix.osx-x86_64-dmd_2085-66874AF3FB189D7222280D5A9FD00EE1/blah .dub/build/application-debug-posix.osx-x86_64-dmd_2085-66874AF3FB189D7222280D5A9FD00EE1/blah.o ../../../.dub/packages/ddash-0.11.1/ddash/.dub/build/unittest-debug-posix.osx-x86_64-dmd_2085-17A0CE6738F65D5CF5A39B0793591577/libddash.a ../../../.dub/packages/ddash-0.11.1/ddash/algorithm/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-347F3AC60651BAB598ACCABDD1B134FC/libddash_algorithm.a ../../../.dub/packages/ddash-0.11.1/ddash/range/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-4ACB945551464FF2F41E70830C443DEA/libddash_range.a ../../../.dub/packages/ddash-0.11.1/ddash/utils/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-37378B094A0203E17D0CC4394DEDEF69/libddash_utils.a ../../../.dub/packages/ddash-0.11.1/ddash/functional/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-045415D91A06B9EA97EF466F23EE2558/libddash_functional.a ../../../.dub/packages/ddash-0.11.1/ddash/lang/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-D5C081D96DABDC69079203481376487A/libddash_lang.a ../../../.dub/packages/ddash-0.11.1/ddash/common/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-DD0F58D7EF71196DD2A1B5B4A5493A33/libddash_common.a ../../../.dub/packages/optional-0.11.1/optional/.dub/build/unittest-debug-posix.osx-x86_64-dmd_2085-37E1E0E388ECBD0246AD2EFF461E5759/liboptional.a ../../../.dub/packages/bolts-0.11.1/bolts/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-C1A02255D87BA8E244266BB680A12BEE/libbolts.a ../../../.dub/packages/sumtype-0.8.3/sumtype/.dub/build/library-debug-posix.osx-x86_64-dmd_2085-DCC08B4F3C573EF2293885A580982517/libsumtype.a -g
Undefined symbols for architecture x86_64:
  "__D5ddash12__ModuleInfoZ", referenced from:
      __D3app12__ModuleInfoZ in blah.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: linker exited with status 1
FAIL .dub/build/application-debug-posix.osx-x86_64-dmd_2085-66874AF3FB189D7222280D5A9FD00EE1/ blah executable
/Library/D/dmd/bin/dmd failed with exit code 1.
```

**Comment by andre2007** [comment]
I am not sure whether it is a dub issue or a dmd / linker issue. You can run 
```dub dustmite --linker-regex="__D5ddash12__ModuleInfoZ" ../red``` 
to have a small reduced test case.

**Comment by aliak00** [comment]
Ok, that was a great tip and took a while. It reduced to a very [weird case](https://github.com/aliak00/linker-ddash-reduced), but, I tried the same case it reduced to with compiler 2.048 and it produced the same linker error. So that was a waste I guess.

I say it's weird because if you remove [this line](https://github.com/aliak00/linker-ddash-reduced/blob/8bc0393dacc409950e962d6c66d8df58fc1ed044/ddash/algorithm/source/ddash/algorithm/package.d#L3) then it runs without any linking error!

I'll try again at some point to get a failing test case that only fails on 2.085...

**Comment by aliak00** [comment]
Ok no. I had forgotten to properly install 2.085. So yes that's the reduced case. Works with the dmd from brew (version 2.084) but fails with a osx installation of 2.085

**Comment by ZombineDev** [comment]
@aliak00 The problem was with the way you had arranged the settings in `dub.json`. Here's a version that works:
* pull request diff: https://github.com/aliak00/linker-ddash-reduced/pull/1/commits
* tree: https://github.com/ZombineDev/linker-ddash-reduced/tree/fix-compilation

Without debugging what exactly changed between dmd 2.084.1 and 2.085.0, IMO the new dmd is still behaving correctly, it's just that internal changes exposed an existing bug in your build process. Here's the diff between the before and after invocations of dmd:
![ddash_dub](https://user-images.githubusercontent.com/3475150/54142004-72b30f80-442f-11e9-94de-c8e49d2aa0cb.png)

There are only two changes:
1. The default build configuration changes from "unittest" to "library" - as far as I can see this has no effect on the actual compilation of the code
2. When the main `ddash` package is build, its `package.d` files gets build as well. This directly matches the missing `__D5ddash12__ModuleInfoZ` linker symbol. 

When a D module is compiled (say `mod.d`), generally speaking, the compiler can produce 3 types of files:
1. object file - `mod.o` on Linux and macOS / `mod.obj` on Windows
2. static library (a.k.a. library archive) - `libmod.a` on Linux on macOS / `mod.lib` on Windows
3. shared/dynamic library - `libmod.a` on Linux / `libmod.dylib` on macOS / `mod.dll` on Windows

Static libraries are simply archives of one or more object files. When working with dub, typically all dependencies are libraries needed to be linked into the main program executable and so dub compiles and links all of their modules into one static library (for each package dependency). That way, dependencies that are already compiled once could be reused by other packages that depend on them (given the same compiler and other important build settings).

There's one `*__ModuleInfoZ` symbol per each object file produced from a D module.

For various reasons, when a D module (say `mod.d`) is imported (in another module, say `main.d`), the compiler expects this module to also be compiled - either together (`dmd mod.d main.d`), or separately (1. `dmd -lib -of libmod.a mod.d` 2. `dmd libmod.a main.d`).

In your case, the `ddash/package.d` file was not linked in - the `importPaths "."` included the `package.d` module, while the `sourcePaths "./algorithm/"` wrongly included the sub-package files, instead of only `package.d`.

As general advice, I suggest following the project structure of other well-tested projects, like vibe.d. In particular it's most straightforward when every package has the following structure: `package/source/module/*.d`. For example with the reduced project:
```
linker-ddash-reduced/
├── blah
│   ├── dub.sdl
│   ├── dub.selections.json
│   └── source
│       └── app.d
└── ddash
    ├── algorithm
    │   ├── dub.sdl
    │   └── source
    │       └── ddash
    │           └── algorithm
    │               ├── package.d
    │               └── stringify.d
    ├── dub.sdl
    └── source
        └── ddash
            └── package.d
```

I hope this helps. I'm closing this issue, since I think that dub is behaving correctly, albeit surprising. Perhaps it would be nice if dub could semantically validate `dub.{json,sdl}` for such issues.

**Comment by aliak00** [comment]
@ZombineDev Wow thank you so much! I could've sworn that the general structure you mentioned is what I had tried once upon a time, and I admit I couldn't get it to work so the root ddash/package.d was a random attempt that seemed to work 😬! But simply putting ddash/package.d into a folder named source made everything work like a charm! Again, thanks a lot for the detailed response :D
